sul-dlss/searchworks_traject_indexer

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/author_spec.rb
=> Adds config and tests for author_sort field.

Gemfile, Gemfile.lock, lib/sdr_stuff.rb, lib/traject/config/sdr_config.rb
=> Initial spike at indexing content from SDR into searchworks

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/stanford_work_dept_spec.rb
=> Adds stanford_work_facet_hsim and stanford_dept_sim fields and tests.

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/format_main_spec.rb
=> Fix format_main_ssim values

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/author_spec.rb
=> Set alternate_script: false for author_person and author_other fields

lib/traject/config/sirsi_config.rb
=> Exclude vernacular data from the pub_search field

lib/traject/config/sirsi_config.rb
=> Join repeated 245a values together

lib/traject/config/sdr_config.rb
Missing from: https://github.com/sul-dlss/sw-indexer/blob/master/lib/sw_mapper.rb#L15
=> add collection type to sdr config

config/schedule.rb, script/commit.sh, script/delete_sdr.sh, script/delete_sdr_preview.sh, script/index_sdr.sh, script/index_sdr_preview.sh, script/index_sirsi_full.sh
also, always write log files from traject... honeybadger just isn't cooperating with output redirection from cron-land.
=> Update traject indexing schedule to try to avoid crashing solr

lib/traject/config/sdr_config.rb
=> Mods reconciliation

Gemfile.lock, lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
=>  Map MODS student work facet data

Gemfile, Gemfile.lock, lib/sdr_stuff.rb, lib/traject/config/sdr_config.rb, spec/fixtures/files/df650pk4327.mods, spec/fixtures/files/df650pk4327.xml, spec/fixtures/files/hn730ks3626.xml, spec/fixtures/files/sg213ph2100.xml, spec/fixtures/files/zz400gd3785.xml, spec/integration/sdr_config_spec.rb
This PR adds new fields needed to support no mods parsing on search results display in https://github.com/sul-dlss/SearchWorks/issues/1987
=> Add Mods display fields

lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
=> only return the year for a given date

lib/translation_maps/db_subjects_map.yaml
=> Add new digital humanities db subject value

lib/marc_links.rb, spec/lib/traject/config/marc_links_spec.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/1940
=> Show $z text for SLS restricted content

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/author_spec.rb
=> Add authorities and rwo uris to the author_struct data

.gitignore, lib/traject/config/sirsi_config.rb, spec/lib/traject/config/title_spec.rb
=>  Parse authorities from 130/240 fields

lib/sirsi_holding.rb, spec/lib/sirsi_holding_spec.rb
=> Fix cutter normalization

lib/traject/config/sirsi_config.rb
Related to https://github.com/sul-dlss/SearchWorks/pull/2308
=> Exclude $x from summary_struct too

config/schedule.rb, lib/traject/readers/purl_fetcher_reader.rb, script/load_sdr_stage.sh, script/process_purl_fetcher_to_kafka.rb, spec/lib/traject/readers/purl_fetcher_reader_spec.rb
This should allow us to rebuild the sw-preview-stage index.
=> Allow the purl_fetcher base url to be configured

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/note_fields_spec.rb
=> Returns values for unmatched vernacular TOC and summary structs

lib/traject/config/sirsi_config.rb
=> Replace a rails-ism

lib/traject/config/geo_config.rb, spec/fixtures/files/ny179kk3075.mods, spec/fixtures/files/ny179kk3075.xml, spec/integration/geo_config_spec.rb
Part of the foundational work needed for https://github.com/sul-dlss/earthworks/issues/628
=> Add content type geo foundation work

lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb
=> Add basic dct_references support for content-type = geo

lib/traject/config/geo_config.rb, spec/fixtures/files/bq589tv8583.mods, spec/fixtures/files/bq589tv8583.xml, spec/integration/geo_config_spec.rb
Part of the work for https://github.com/sul-dlss/earthworks/issues/592
=> Support indexing collections as individual records in EarthWorks

lib/traject/config/geo_config.rb, spec/fixtures/files/mc977kq8162.xml, spec/integration/geo_config_spec.rb
=> Add a reference to the collection object for geo objects.

lib/traject/config/geo_config.rb
=> Uniq multi-valued metadata values

lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb
See https://github.com/sul-dlss/gis-robot-suite/pull/329/files#diff-d36b143944a66049fa5d65e6d5deb191L114-L116
=> LineStrings should be indexed as Lines for content type geo

lib/traject/writers/solr_better_json_writer.rb
=> Add a little back-off to  space out batches-send-as-individual-records

lib/marc_links.rb, lib/traject/config/sirsi_config.rb
=> Index 956 fields into marc_links

lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb
Part of https://github.com/sul-dlss/earthworks/issues/797
=> Index the license, use and reproduction, and copyright statements from mods_display

lib/traject/config/sirsi_config.rb
=> Add 647 to subject fields to be indexed

lib/translation_maps/location_map.properties
Add SCIFI location.
Closes #2775
=> Add SCIFI location to location_map.properties

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/physical_spec.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/2813
=> Add subfield 3 to the physical display field

lib/traject/config/sirsi_config.rb
=> Convert MARC 999 direct refs in sirsi_config to use holdings class

lib/traject/config/folio_config.rb
…and do it after we set up our settings so we don't have to jump through hoops
=> Let traject load the sirsi config, 

config/boot.rb
…for ease of local development if nothing else.
=> Allow overriding settings using environment variables 

lib/traject/extractors/folio_kafka_extractor.rb
=> Guard against missing instance ids

lib/folio_record.rb, lib/traject/config/folio_config.rb, lib/traject/readers/folio_postgres_reader.rb, spec/integration/folio_config_spec.rb
=> handle the suppressFromDiscovery flag on instances, holdings, or items

lib/folio_record.rb, lib/traject/readers/folio_postgres_reader.rb
Proof of concept for #681. Will need an actual spec for the instance-derived MARC records some day.
=> Index records without holdings, items, or source record data

lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/integration/folio_config_spec.rb
=> Wire up FOLIO date_cataloged to instance catalogedDate

lib/traject/config/folio_config.rb
=> Require Rails' additional time methods

lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb
- Parameterize purl, stacks, and geoserver URLs in geo config
- Style cleanup with rubocop
lmk if you think new tests are needed; I wasn't sure how to mock traject settings in rspec so didn't add them.
see #742 for context
=> Make seams in geo config for pointing to staging servers

config/settings.yml
These stopped being used after #764
=> Cleanup unused environments

README.md
=> Remove markup attributes that github strips out

bin/console
This is useful for debugging on the server, similar to bin/rails console
=> Add a console script

lib/call_numbers/shelfkey.rb, lib/call_numbers/shelfkey_base.rb
Ref https://github.com/sul-dlss/searchworks_traject_indexer/pull/784/files#r1170390283
=> Refactor to_shelfkey to be simpler

script/index_single_item_by_id.rb
Ref https://github.com/sul-dlss/searchworks_traject_indexer/pull/784/files\#r1170543652
=> Refactor index_single_item_by_id

spec/integration/compare_sirsi_and_folio_spec.rb
we're adding an additional the FOLIO value
=> Ignore the collection field when comparing sirsi + folio records

lib/traject/readers/folio_reader.rb
We wrote a helper method on FolioClient that has this logic, so
no need to repeat it in the FolioReader
=> Update FolioReader to use an existing helper method

lib/marc_links.rb
Vaguely related to some refactoring I want to do for #767
=> Prefer match? over =~

lib/folio_record.rb, lib/traject/readers/folio_postgres_reader.rb
=> Retrieve item notes and include them in the item_display field

lib/folio/mhld_builder.rb, lib/folio_record.rb, spec/integration/folio_config_spec.rb
=> Copy public_note to every line in mhld_display if present

lib/traject/config/sdr_config.rb
Ref https://github.com/sul-dlss/SearchWorks/issues/3133
=> Cache the collection name consistently

lib/folio/eresource_holdings_builder.rb, lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/fixtures/files/a12451243.json, spec/integration/folio_config_spec.rb, spec/lib/folio/eresource_holdings_builder_spec.rb
=> Create holdings for electronic resources in FOLIO

lib/traject/readers/folio_postgres_reader.rb
=> Query more tables for change dates

lib/folio/mhld_builder.rb, spec/integration/folio_config_spec.rb
=> Fix case where holdingsStatementsForSupplements doesn't have a statement

lib/folio/mhld_builder.rb, spec/integration/folio_config_spec.rb
=> Don't create mhld_display when there are no holdings statements

lib/traject/readers/folio_postgres_reader.rb
Fixes the issue that @cbeer found in records like https://searchworks-folio-dev.stanford.edu/view/14369502
=> Filter Bound-with query for not null parents

.github/workflows/ruby.yml, Jenkinsfile, config/deploy.rb
=> Rename default branch to main

lib/folio/mhld_builder.rb, spec/lib/folio/mhld_builder_spec.rb
=> Handle the case where the piece does not have enumeration

config/boot.rb, lib/traject/config/folio_config.rb, lib/traject/readers/folio_json_reader.rb
=> Zeitwerk fixes

.github/workflows/ruby.yml
=> Stop testing on Ruby 3.1

lib/translation_maps/location_map.properties
Part of https://github.com/sul-dlss/SearchWorks/issues/3211
=> Add PAGE-FC location translation

lib/folio/mhld_builder.rb, lib/folio_record.rb, lib/traject/readers/folio_postgres_reader.rb, spec/integration/folio_config_spec.rb, spec/lib/folio/mhld_builder_spec.rb
=> Only show latest received for open and ongoing orders

lib/traject/readers/folio_postgres_reader.rb
=> Add clause to exclude shadowed items from being indexed

lib/traject/readers/folio_json_reader.rb, spec/fixtures/files/whodunit.json
And re-export the whodunit.json fixture
=> Provide directions about making exports

lib/folio_record.rb, lib/traject/config/folio_config.rb, lib/traject/readers/folio_postgres_reader.rb, spec/fixtures/files/folio_basic.json, spec/fixtures/files/folio_bw_child.json, spec/fixtures/files/folio_bw_child_see-other.json, spec/integration/folio_config_spec.rb, spec/lib/folio_record_spec.rb
... and give the bound-with data a structure that's more like the regular instance/item objects.
=> Make bound-with data a property of the holdings object

lib/traject/readers/folio_postgres_reader.rb
Fixes #1008
It's not clear to me how this happens 🤷‍♂️
=> Guard against nil items and holdings

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/item_info_spec.rb
=> Index item_display_struct in addition to the original delimited value

lib/traject/readers/folio_postgres_reader.rb
... in  holdings statements and circulation notes
=> Suppress administrative notes entirely, and filter out staff-only notes

lib/traject/config/sirsi_config.rb
=> Guard against nil barcodes

lib/sirsi_holding.rb, lib/traject/config/sirsi_config.rb
.. to make it easier to pass in course reserves details from FOLIO
=> Extract SirsiHolding#to_item_display_hash 

lib/folio_record.rb, spec/lib/folio_record_spec.rb
=> Build out better information for on-order stub records

lib/folio/mhld_builder.rb, spec/lib/folio/mhld_builder_spec.rb
=> Filter out holdings that have MIGRATE-ERR location

lib/sirsi_holding.rb, spec/lib/sirsi_holding_spec.rb
This may happen for on-order items
Fixes #1049
=> Handle nil call_numbers

lib/folio_record.rb
We already determined there are no items as the first step in the method
=> Remove unnecessary check.

config/schedule.rb
=> Schedule a FOLIO full dump every month

lib/folio/eresource_holdings_builder.rb, lib/folio_record.rb, lib/sirsi_holding.rb, lib/traject/config/sirsi_config.rb, spec/lib/folio/eresource_holdings_builder_spec.rb
We can use the other fields in SirsiHolding instead
=> Remove SirsiHolding#tag

lib/folio_record.rb, spec/lib/folio_record_spec.rb
=> Parse identifiers when deriving MARC from FOLIO instance records

lib/locations_map.rb, spec/integration/folio_config_spec.rb
=> Exclude some mapped FOLIO locations from being translated to Symphony codes

lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
=> Call Traject's first_only on arrays rather than nodesets

lib/traject/config/folio_config.rb
=> Wire up the kafka.consumer configuration

README.md
Bump version to 3.2; remove jruby mention
=> Update ruby versions in README

spec/lib/traject/config/database_az_subject_spec.rb, spec/lib/traject/config/format_main_spec.rb, spec/support/result_helpers.rb
=> Instance statistical code test fixes

lib/sirsi_holding.rb, spec/integration/skips_spec.rb, spec/lib/traject/config/callnum_facet_spec.rb
=> There is no longer a library named PHYSICS in Folio

spec/lib/traject/config/callnum_facet_spec.rb
This helps us move away from dependence on Marc by reducing calls to record_with_999
=> Refactor Dewey call number tests

spec/lib/traject/config/database_az_subject_spec.rb
This is not necessary for the tests
=> Remove 999 from database_az_spec

spec/lib/traject/config/genre_spec.rb
Slightly more idiomatic syntax for rspec
=> Refactor genre_spec to use a subject

lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/integration/folio_config_spec.rb, spec/lib/traject/config/access_spec.rb
(even if those items are suppressed from discovery)
=> Don't create on-order stubs if there are any item records

spec/lib/traject/config/preferred_barcode_spec.rb
The same test appears on line 22
=> Remove duplicate test

spec/factories/holdings.rb, spec/lib/traject/config/format_main_spec.rb
=> Remove all 999 fields from format_main_spec

spec/lib/traject/config/format_main_spec.rb, spec/lib/traject/config/format_physical_spec.rb, spec/lib/traject/config/item_info_spec.rb, spec/lib/traject/config/preferred_barcode_spec.rb
=> Avoid testing with a 999 with ASIS as a scheme

lib/folio_record.rb
=> Handle courses without listed instructors

spec/integration/all_search_spec.rb, spec/lib/traject/config/location_facet_spec.rb
Drop the 852c tests as Folio doesn't do this
=> Convert location_facet spec to use the folio config

spec/lib/traject/config/preferred_barcode_spec.rb
=> Remove MARC 999 fields from preferred_barcode_spec

lib/folio/mhld_builder.rb, spec/lib/folio/mhld_builder_spec.rb
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/1190
=> Filter MHLD 'latest' to actually received pieces

lib/traject/common/marc_utils.rb
=> Exclude subfield 7 from 1xx and 7xx values

spec/lib/traject/config/holdings_spec.rb
This makes it easier to understand how the test is working
=> Don't stub holdings where we don't need it

spec/factories/holdings.rb, spec/lib/traject/config/format_main_spec.rb, spec/lib/traject/config/item_info_spec.rb
=> Stub holdings records instead of relying on MARC 999

lib/folio_holding.rb
Adds #1173 to the extracted `FolioHolding` classes
=> Expand TEMP_CALLNUM_PREFIX to match the actual migrated data

lib/folio_holding.rb, spec/integration/folio_config_spec.rb, spec/lib/folio_holding_spec.rb
so we can drive Searchworks behaviors without needing to pull back all of the `holdings_json_struct`.
Fixes #1093
=> Add FOLIO-isms to the FoldingHolding#to_item_display_hash

lib/traject/readers/folio_postgres_reader.rb
https://github.com/sul-dlss/operations-tasks/issues/3523
=> Tweak postgres session options

lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/lib/traject/config/folio_course_reserves_spec.rb
This lets us match Folio course reserves data from the API with the Solr record
Ref https://github.com/sul-dlss/SearchWorks/issues/3736
=> Index the folio course id for course reserves

spec/integration/geo_config_spec.rb, spec/lib/sdr_events_spec.rb
I reformatted these using rubocop-rspec and made them easier to read.
=> Clean up formatting and simplify tests

lib/folio/marc_record_instance_mapper.rb
Related to upstream changes from https://folio-org.atlassian.net/browse/MODQM-276
=> Handle new poppy data structures

lib/traject/config/geo_config.rb, spec/fixtures/files/jk681br3989.xml, spec/integration/geo_config_spec.rb
See https://github.com/sul-dlss/gis-robot-suite/issues/657
=> Add WFS url to references for GeoJSON content in Earthworks

lib/traject/config/folio_config.rb
At least some of the sw_index_tests expect to search for words from the title + topics 🤷‍♂️
=> Add topic values to bib_search

config/settings.yml, lib/traject/readers/folio_postgres_reader.rb, script/process_folio_postgres_to_kafka.rb
... and use it to pick the right tables to query for changes
=> Add a folio.version setting to FolioPostgresReader 

lib/folio/eresource_holdings_builder.rb, lib/marc_links.rb, lib/traject/config/folio_config.rb
Removes GSB URL filtering as requested in #864.
=> Remove GSB URL filtering

lib/traject/readers/folio_postgres_reader.rb
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/1351
=> Only use complete_updated_date field for poppy

lib/traject/config/folio_config.rb
Align block variable name with changes in https://github.com/sul-dlss/searchworks_traject_indexer/pull/1354
=> Rename block variable from holding to item

lib/sdr_events.rb, lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb, spec/lib/sdr_events_spec.rb
=> Report the indexing target when sending events to SDR

lib/traject/config/geo_config.rb
See https://github.com/sul-dlss/gis-robot-suite/issues/817
=> Support index maps with .geojson extension

spec/factories/holdings.rb, spec/lib/traject/config/preferred_barcode_spec.rb
... and also clarify when we're testing serials vs non-serials
=> Split the call number enumeration from the base callnumber

lib/folio_item.rb, lib/traject/readers/folio_postgres_reader.rb, spec/factories/holdings.rb, spec/lib/traject/config/item_info_spec.rb
This is required in order to implement the display changes called for in https://github.com/sul-dlss/SearchWorks/issues/3200
=> Add callNumber, volume, enumeration, chronology to boundWith 

lib/public_cocina_record.rb, spec/fixtures/files/bb021mm7809.json, spec/lib/public_cocina_record_spec.rb
As a prerequisite for serializing ardvark data (in order to upgrade earthworks) this creates the initial (and basic) PublicCocinaRecord class.
=> Add initial basic PublicCocinaRecord class

lib/traject/config/folio_config.rb, spec/lib/traject/config/folio_course_reserves_spec.rb
No longer needed after https://github.com/sul-dlss/SearchWorks/issues/3736
=> Remove unused fields courses_json_struct and crez_course_info

lib/traject/config/folio_config.rb, spec/factories/holdings.rb, spec/lib/traject/config/item_info_spec.rb
For drawing the modal in https://github.com/sul-dlss/SearchWorks/issues/3200
=> Index bound with parent item ids

lib/folio_item.rb, spec/lib/traject/config/callnum_facet_spec.rb, spec/lib/traject/config/item_info_spec.rb, spec/lib/traject/config/preferred_barcode_spec.rb
All our SHELBYTITLE locations have the E in FOLIO.
=> Dropping the E in SHELBYTITL was a Symphony-ism

lib/folio_item.rb
https://github.com/sul-dlss/searchworks_traject_indexer/pull/1422 needs this to be happy.
=> Disable rubocop AbcSize

lib/traject/readers/folio_postgres_reader.rb
Otherwise Searchworks shows items on course reserves forever. Fixes #1376
=> Filter course reserves to courses that end in the future

.rubocop_todo.yml, Gemfile.lock, lib/purl_record.rb, lib/traject/readers/druid_reader.rb, lib/traject/readers/kafka_purl_fetcher_reader.rb, spec/integration/geo_config_spec.rb, spec/integration/sdr_config_spec.rb, spec/lib/traject/readers/kafka_purl_fetcher_reader_spec.rb, spec/lib/traject/writers/solr_better_json_writer_spec.rb
The purl encompases the PublicCocina and the PublicXml
=> Rename PublicXmlRecord to PurlRecord

lib/traject/config/folio_config.rb, spec/lib/traject/config/author_title_spec.rb
This needs to wait for the searchworks PR + associated sul-solr schema updates.
=> Add indexing for the best_author_title_search field

lib/folio_item.rb, lib/traject/config/folio_config.rb, spec/lib/traject/config/format_main_spec.rb
=> Use FOLIO Holding Type = Equipment

Capfile, Gemfile, Gemfile.lock
Same change as here for the same reason https://github.com/sul-dlss/earthworks/pull/1076
Unbreak deployment
=> remove capistrano rvm dependency

lib/traject/config/geo_aardvark_config.rb, spec/integration/geo_aardvark_config_spec.rb
See https://app.honeybadger.io/projects/49895/faults/109287482
=> Re-implement ID hashing of Geo content for sitemap generation

README.md
Removes some outdated pre-folio examples and adds some more
recent techniques for indexing items from SDR.
=> Update README instructions for running traject in local dev

lib/traject/config/geo_aardvark_config.rb, spec/fixtures/files/cd502cx8669.json, spec/fixtures/files/cd502cx8669.meta_json, spec/integration/geo_aardvark_config_spec.rb
=> Geo Aardvark: skip records with no bounding box

lib/traject/config/geo_aardvark_config.rb, spec/integration/geo_aardvark_config_spec.rb
This reverts commit 91e574a9e967d2b8af87252b51bedb86645b361b.
=> Revert "Geo Aardvark: Reverse the boolean logic for gbl_georeferenced_b"

lib/translation_maps/geo_theme.yaml
=> Add more mappings for the geo "theme" field

lib/traject/macros/cocina.rb, spec/fixtures/files/bq589tv8583.meta_json, spec/integration/geo_aardvark_config_spec.rb
=> fix searchworks url formation

lib/traject/config/folio_config.rb
Per Kevin, include 45rpm discs in the Vinyl disc list.
=> Expand the definition of Vinyl disc

lib/folio/sortable_date_parser.rb, spec/lib/folio/holdings_spec.rb
=> Handle YYYY:MON/MON patterns when figuring out the latest received

lib/marc_links.rb, spec/lib/traject/config/marc_links_struct_spec.rb
part of https://github.com/sul-dlss/SearchWorks/issues/4606
=> add note field to marc links

config/schedule.rb
While we're in a workcycle, getting a consistent + regularly updated FOLIO index seems like it'd be nice to have.
=> Do nightly full reindexing in -stage

lib/folio/holdings.rb, spec/lib/folio/holdings_spec.rb
=> Handle holding record comparison when enumeration is nil

lib/folio_item.rb, spec/lib/folio_holding_spec.rb
closes #1594
How this maps to SearchWorks
=> update public_note to look at holdings note for bound_withs

lib/traject/config/folio_config.rb, spec/lib/traject/config/format_main_spec.rb
=> Add 'Loose-leaf' as a format

lib/traject/config/folio_config.rb
=> Add documentation about building_location_facet_ssim

lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
This allows us to use codes to display locations in SearchWorks
See https://github.com/sul-dlss/SearchWorks/pull/4858
=> Index SDR into the library_code_facet_ssim

.rubocop_todo.yml, lib/traject/common/marc_utils.rb, lib/traject/config/folio_config.rb, spec/lib/traject/config/note_fields_spec.rb
=> check indicator1=4 for 520 content advice vernacular fields

lib/traject/config/folio_config.rb, spec/integration/folio_config_spec.rb
This follows on to #1612 and supports sul-dlss/SearchWorks#4858
=> Add SDR to library_code_facet_ssim if there is a purl in the 856

lib/folio/mhld_builder.rb, spec/lib/folio/mhld_builder_spec.rb
=> Include bound-with child holding statements at the location of the bound-with parent

lib/marc_links.rb, spec/lib/traject/config/marc_links_struct_spec.rb
waiting until https://github.com/sul-dlss/SearchWorks/issues/4606 is done.
=> remove finding aid logic

README.md
This was messing me up during setup!
=> Update tunnel port in README

lib/traject/config/sdr_config.rb, script/remediate_sdr_formats.rb
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/1645
=> Quickly map the old format_main_ssim values to new format_hsim values.

lib/traject/config/folio_format_config.rb
- Video games were indexing as website (copypaste)
- Collapse 3rd level facets into 2nd level groups
- Migrate statistical code check for databases
=> Fix format indexing

lib/traject/config/folio_format_config.rb
... still to be verified, but maybe better to get it in and then remove it?
=> Restore Database mapping for one condition

lib/folio_item.rb, lib/utils.rb, spec/lib/utils_spec.rb
… by trying harder to splitting at 'V.' or some other whitespace or punctuation.
Related to https://github.com/sul-dlss/SearchWorks/issues/5065
=> Try to be a little better about picking the longer common call number piece
