sul-dlss/searchworks_traject_indexer

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/title_spec.rb
Per solrmarc-sw config, trailing periods should be preceded by four or more letters.
=> Uses trim_punctuation_custom for title display fields.

lib/traject/config/sirsi_config.rb
Fixes #118 .
I'm not seeing issues with other `splits` at the moment just this one. Ran indexing locally to confirm.
=> no scan to prevent thread issues on jruby

lib/traject/config/delete_config.rb, lib/traject/config/sdr_config.rb, lib/traject/config/sdr_delete_config.rb, lib/traject/config/sirsi_config.rb
It turns out HTTPClient uses a shared session pool that doesn't allow run-time changes to timeouts, etc that traject tries to use; instead, we need to set the receive timeout for our worst-case and hope for the best.
=> Provide our own HTTPClient instance with a timeout appropriate for long-running commits

lib/traject/config/sdr_config.rb, spec/fixtures/files/vv853br8653.xml, spec/fixtures/files/zc193vn8689.xml, spec/integration/sdr_config_spec.rb
This aims to fix https://github.com/sul-dlss/SearchWorks/issues/2041 by providing a more robost schema.org dataset record for content-type geo. The assumptions made in this metadata reflect valid assumptions for all content type geo.
=> adds more robost schema.org record for geo content

script/index_sirsi_catchup.sh
If a full reindex of MARC data completes before 6am, the hourly file
from the previous day will be indexed after the nightly file that was
generated just before midnight. There's a chance that the data in the
hourly file is outdated versus the data in the nightly file. We should
rely on the cronjob to index the latest hourly file.
=> Removes index_sirsi_hourly.sh from catchup.sh.

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/note_fields_spec.rb
Fixes [VUF-7003](https://jirasul.stanford.edu/jira/browse/VUF-7003)
=> Avoid splitting TOC data on strings like 'v. 1. asdfasdf'

lib/traject/writers/solr_better_json_writer.rb, spec/lib/traject/writers/solr_better_json_writer_spec.rb
I don't really understand how this happens, presumably some incredibly mangled data, but this'll fix at least one of the crashes that's getting reported to honeybadger..
=> Guard against deletes for a document without an id

lib/traject/config/sirsi_config.rb
I ported format_main_ssim logic into Lane's Java-based ETL process which will be used to index SearchWorks data for [Lane Search](https://lane.stanford.edu/) later this year. Monitoring for changes will primarily be a Lane responsibility, but please consider adding a comment like this one to document this dependency and ensure that SUL's data is properly represented in Lane's system.
=> add comment about Lane's ETL dependency on format_main_ssim code

lib/traject/config/geo_config.rb, spec/fixtures/files/qy240vt8937.mods, spec/fixtures/files/qy240vt8937.xml, spec/integration/geo_config_spec.rb
This PR does the following:
- Adds coordinate parsing envelopes and ensures only the first (GeoBlacklight only supports single valued I think)
- Adds single valued years for usage in range slider
=> Enhancements to indexing based off of feedback from geo team

lib/traject/config/geo_config.rb
```
./lib/traject/config/geo_config.rb:183:in `block (2 levels) in load_config_file': undefined method `first' for nil:NilClass (NoMethodError)
```
The skip doesn't stop execution, so we need just a little bit more specific control flow here.
=> Better control flow for presence of solr_geom

lib/traject/config/geo_config.rb
https://purl.stanford.edu/cw692sh3587.mods
```
./lib/traject/config/geo_config.rb:140:in `block (3 levels) in load_config_file': undefined method `gsub' for nil:NilClass (NoMethodError)
from ./lib/traject/config/geo_config.rb:139:in `map'
from ./lib/traject/config/geo_config.rb:139:in `block (2 levels) in load_config_file'
```
=> Handle empty author named elements which could cause processing to fail

lib/sdr_stuff.rb, lib/traject/readers/kafka_purl_fetcher_reader.rb, spec/lib/traject/readers/kafka_purl_fetcher_reader_spec.rb
There's an issue with some old data in the kafka topic where the catkey is recorded as an empty string (triggering a delete). This PR  guards against it, because it's easier to do that than to make sure we wipe out all the bad data.
=> Ignore empty catkeys

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/access_spec.rb
Fixes #429 
The first 3 commits make the code a bit more "open" to this change, and just the last one adds it.
Also, I got the 👍 from @saseestone about 6ff2a91 and treating `SPEC-INPRO` like a current and home location.  More details in the commit message.
=> Remove ENDPROCESS items from being "On order"

script/seed_hashed_id_field.rb
Here's a quick, one-off script to seed the hashed_id_ssi fields with data by feeding it  a list of document ids to run an atomic update on.
=> Add a script to seed hashed_id_ssi fields

Gemfile, Gemfile.lock, lib/traject/config/sirsi_config.rb, script/load_hathifiles.rb, script/seed_hathi_data.rb
Augment solr documents with hathitrust identifiers (for items available to read, at least ) by looking them up by OCLC  number in a locally managed database.
=> Query our HT database to look up the htid for our items

lib/marc_links.rb, lib/traject/config/sirsi_config.rb, spec/lib/traject/config/access_spec.rb, spec/lib/traject/config/marc_links_spec.rb, spec/lib/traject/config/url_spec.rb
We were handling "blank" a indicator2 a bit differently between the marc_links_struct and the url_fulltext field (which is used to determine of Access = Online)
This unifies that approach and simplifies it a bit.
We are no longer trying to treat "blank" indicator2 as full-text anymore in the Online facet.  We only appeared to be in the code before in the marc_links_struct, however a nil or blank indicator2 comes through as " " (failing the `.empty?` check), so was always falling through as falsey for the full-text check anyway (the behavior we likely wanted).
According to https://www.loc.gov/marc/bibliographic/bd856.html, an indicator2 of 0 or 1 is either the resource itself or a version of the resource.  We then take those 856s and cast out any links that have labels that arouse …
=> Simplify and and unify logic for when a link is considered full-text.

.github/workflows/ruby.yml, Gemfile, Gemfile.lock, lib/sdr_stuff.rb, lib/traject/config/sirsi_config.rb
This PR also removes `eye` and `config` from the Gemfile; there's a semi-convincing argument to be made that they aren't really part of the application, just part of how it's deployed, and don't belong here (plus... there's some weird bundler/jruby/eye interaction going on 🤷‍♂️ ).
We'll be moving off `eye` sooner rather than later anyway.
=> Update + test against Ruby 3

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/sirsi_config_spec.rb
It turns out our existing indexing isn't the most useful for finding records with repeated subfields, so here we also index (using a quasi-marcspec syntax) just the presence of the tag/code too.
=> Separately index field/subfield pairs

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/note_fields_spec.rb
... until one of the potential formats is successful to avoid over-splitting the data.
=> Only apply chapter splitting regexes 

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/note_fields_spec.rb
e.g. https://searchworks.stanford.edu/view/9629895
=> Make sure chapter numbers are in a non-matching group to avoid extra splitting

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/item_info_spec.rb
This should make it easier to find appropriate fixture objects and other weird edge cases for e.g. requestability
=> Add additional indexing for selecting items with particular types and current locations

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/author_spec.rb
=> Remove double quotes from contributor search value in author_struct.

lib/sdr_stuff.rb, spec/fixtures/files/nn217br6628.xml, spec/integration/geo_config_spec.rb
Here's a proposed fix for #582.
Best I can tell geo objects get sent to either the public or restricted geoserver based only on `access` with no regard for any restrictions, such as `no-download`. At least that's what appears to be happening here: https://github.com/sul-dlss/gis-robot-suite/blob/main/lib/gis_robot_suite.rb#L135
With this change, `dc_rights_s` is set to `Public` if there is an object level world node (first value of `Dor::RightsAuth.parse(rights_xml).world_rights`). Otherwise, it will check whether there is an object-level group/stanford node (first value of `Dor::RightsAuth.parse(rights_xml).stanford_only_rights`).
Could use a close eye on this PR.
=> Set dc_rights_s based on access (world/stanford) regardless of download restrictions. Closes #582.

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/note_fields_spec.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/2848
This PR pulls out the regex logic into its own method, and applies that to both 505 and 880 TOC fields. Before, the 880 field was only getting checked by a minimal regex, instead of the whole array of regexes applied to the 505 field.
=> Split TOC data in the same way for 505 and 880 fields

lib/traject/config/sirsi_config.rb
Small PR to cleanup an outdated method that I came across doing work for #635
The issue that the workaround addressed in jruby has been closed.
=> Remove regex_split workaround method

lib/marc_links.rb, spec/lib/traject/config/marc_links_spec.rb
This solution assumes that we can identify a Casalini link by the presence of:
`<subfield code='x'>CasaliniTOC</subfield>` OR `<subfield code='z'>(source: Casalini)</subfield>`
It also assumes that we may not be able to count on the presence of $z for all Casalini links so we retain the logic related to generating the "(source: Casalini)" text within `MarcLink` rather than plucking it from the MARC record.
Fixes: https://github.com/sul-dlss/SearchWorks/issues/2863
=> Display "(source: Casalini)" only once.

lib/sdr_stuff.rb, lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
New fields:
`dor_content_type_ssi`
`dor_resource_content_type_ssim`
`dor_file_mimetype_ssim`
`dor_resource_count_isi`
`dor_read_rights_ssim`
Partially addresses https://github.com/sul-dlss/SearchWorks/issues/2885
=> Add fields to capture DOR Public XML info: content types, resource counts, rights, etc.

lib/marc_links.rb, spec/lib/traject/config/marc_links_spec.rb
The other way to fix this would be to encode the single quote as `%27`, but it seems preferable to just use double quotes to enclose the HTML attributes since un-encoded double quotes are not valid in URLs.
Before:
```
<a title='' href='https://www.africamuseum.be/sites/default/files/media/docs/research/publications/rmca/online/documents-social-sciences-humanities/L'Echo_des_Monts_et_Vallees.pdf'>www.africamuseum.be</a>
```
After:
```
<a title="" href="https://www.africamuseum.be/sites/default/files/media/docs/research/publications/rmca/online/documents-social-sciences-humanities/L'Echo_des_Monts_et_Vallees.pdf">www.africamuseum.be</a>
```
Fixes: https://github.com/sul-dlss/SearchWorks/issues/2962
=> Use double quotes to enclose HTML attributes in marc_links_struct; fixes #2962

lib/folio_record.rb, lib/traject/common/constants.rb, lib/traject/config/folio_config.rb, spec/lib/folio_record_spec.rb
See #662 for a list of junk tags, and https://consul.stanford.edu/display/SYSTEMS/Data+Feed+to+SearchWorks#DataFeedtoSearchWorks-PostProcessing for a detailed explanation of processing steps that we're hoping to move to traject (of which this is one).
- Strip parsedRecord from folio_json_struct
- Implement junk tag stripping for Folio records
We ultimately decided not to strip some of the things that were in the list, including 001, 003, and the 8xx fields. It turned out that some of this data was actually used (e.g. for MHLDs in the case of the 8xx) or at least not harmful (in the case of 001 and 003).
=> Strip junk tags from folio records

lib/folio_client.rb, lib/folio_record.rb, lib/traject/config/folio_config.rb, lib/traject/extractors/folio_kafka_extractor.rb, lib/traject/readers/folio_reader.rb, lib/traject/readers/kafka_folio_reader.rb, spec/integration/folio_config_spec.rb, spec/lib/folio_record_spec.rb
This brings over the new `FolioRecord#as_json` serialization and updates the `folio_json_struct` data structure etc in preparation for a more descriptive intermediate representation of FOLIO instances.
0a5e7f5a9b5f77181ceb6da4b918395a57a4d175 also adds a default to ensure we get records even if the timestamp isn't supplied.
=> Cherry-pick useful refactoring from #692

lib/traject/extractors/folio_kafka_extractor.rb
This seems like it gets us slightly better throughput (~20%).
=> Increase the kafka batch size for FOLIO records

Gemfile, Gemfile.lock, config/settings.yml, lib/traject/extractors/folio_kafka_extractor.rb, lib/traject/extractors/marc_kafka_extractor.rb, lib/traject/extractors/purl_fetcher_kafka_extractor.rb, lib/traject/readers/folio_postgres_reader.rb, script/process_folio_postgres_to_kafka.rb
Parallelizing with 8 threads is ~4x faster; it's unclear at the moment why it isn't even better, but hopefully this lets us fail faster when doing data loading.
=> Parallelize the postgres data load into kafka by sharding on the instance id

.github/workflows/ruby.yml
Addresses the following github actions warnings:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2
> 
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> 
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output- …
=> Set actions/checkout to v3

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/subject_spec.rb
Metadata is moving some collection data from 690 to 795. To support the transition, we should treat 795 as if it was a 690 (indexed into the same places) and also create some fields for future faceting.
=> Index 795 fields as collection data

lib/traject/config/geo_config.rb
=> Don't skip indexing druids with catkeys for EarthWorks

lib/call_numbers/call_number_base.rb, spec/lib/traject/config/item_info_spec.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/3102
N.S. was already being retained, but was untested. This change retains both N.S. and O.S. before the volume number for shelved by title call numbers and adds test coverage.
=> Retain O.S. designation before volume number

Gemfile, Gemfile.lock
It is a transitive dependency, so we don't need it in Gemfile
=> Remove unused direct dependency rexml

config/settings.yml, script/process_folio_to_kafka.rb
It's now set as an environment variable so that the secrets can be in Vault. This will allow us to manage configs in shared_configs
=> Remove okapi_url from settings

lib/folio_record.rb
So that we don't have to re-filter ever time this is referenced
=> Cache filtered items

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/note_fields_spec.rb
Fixes https://github.com/sul-dlss/SearchWorks/issues/3103
See https://www.loc.gov/marc/bibliographic/bd505.html for indicator/status names
=> Change contents label according to 505 indicator

Gemfile, Gemfile.lock, README.md, lib/traject/config/folio_config.rb, lib/traject/readers/folio_json_reader.rb
traject-plus offers a simple JsonReader, so this just subclasses it
to generate `FolioRecord` from the files passed to it.
Adds documentation to the README about how you could use it, after
e.g. using #823 (or the APIs) to get the record and save it as JSON.
=> Create a Traject::FolioJsonReader for working with local JSON files

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/holdings_spec.rb
FOLIO doesn't have a holdings or order pieces when we're missing the data, so we can't generate anything. That's fine, because Searchworks ignores `mhld_display` data without data:
https://github.com/sul-dlss/SearchWorks/blob/master/lib/holdings/mhld.rb#L15-L19
Instead of indexing data we just ignore, let's not generate it in the first place.
=> Suppress SIRSI MHLD indexing if the library/location has no data

lib/marc_links.rb
`link` and `link_field` are the same. More refactoring to prepare for work on #767
=> Use link var consistently

lib/marc_links.rb
This reduces some duplication within the MarcLinks::Processor class. It will also allow us to remove some duplicated logic in sirsi_config.rb when creating `url_fulltext`, `url_suppl`, `url_sfx`, and `url_restricted` (in a future PR) -- another step toward #767.
=> Add constants to MarcLinks module for matching MARC link field values

script/process_folio_postgres_to_kafka.rb
Since we're using a non-blocking file lock, we must check the return value
=> Abort the program if a lock can not be acquired

traject.eye
This will prevent syntax errors on character class literals
Fixes #841
=> Explicitly set the language in the eye config

script/process_folio_postgres_to_kafka.rb
This explains as Index Only Scan using instance_pkey on instance vi rather than Seq Scan on instance vi
=> Compare using binary rather than casting to text

lib/traject/config/sirsi_config.rb
We don't need a separate `to_field` definition for `856` and `956` links since the `MarcLinks::Processor#.link_is_fulltext?` method  applies the right logic for both fields.
=> Combine to_field definition for 856 and 956 fields

lib/folio_record.rb, lib/traject/config/folio_config.rb, lib/traject/readers/folio_postgres_reader.rb, spec/fixtures/files/whodunit.json, spec/integration/folio_config_spec.rb, spec/lib/traject/config/folio_course_reserves_spec.rb, spec/lib/traject/config/sirsi_course_reserves_spec.rb
- Rename sirsi course reserves spec to distinguish it from FOLIO
- Index course reserve fields from FOLIO records
See #667, in particular the final comment, for an explanation of why we aren't modifying `item_display` and `building_facet` in FOLIO with crez info. If these assumptions are correct, then this finishes #667.
#833 should be merged first, otherwise the impact from this won't be visible because we'll still be using the logic from the sirsi config.
=> Index course reserve data from FOLIO

spec/integration/compare_sirsi_and_folio_spec.rb
#854 is indexing empty arrays into previously unpopulated CREZ fields. We can just ignore this discrepancy 🤷‍♂️
=> Treat nil + empty arrays as equivalent

lib/mhld_field.rb, lib/traject/config/sirsi_config.rb, spec/lib/traject/config/holdings_spec.rb
Part of https://github.com/sul-dlss/SearchWorks/issues/1974. Per JV, we shouldn't duplicate the display of latest received or public note. 
I've ignored the FOLIO MHLD indexing for the moment; a future ticket will cover the remaining differences, but hopefully this PR makes it a little clearer what we are currently doing and brings us closer to displaying the data the way we want to..
=> Refactor mhld_display indexing and remove duplicated notes display

README.md
So that it uses the current directory (symlink), rather than the working directory.
The working directory disappears after 5 deploys and it is cleaned up.
=> Update service generation code

lib/folio/mhld_builder.rb
Follow-on to #875 . It seems reasonable to proactively address this too.
=> Guard against missing statements for indexes

lib/folio_record.rb, lib/traject/config/folio_config.rb, lib/traject/readers/folio_postgres_reader.rb, spec/integration/folio_config_spec.rb, spec/lib/folio_record_spec.rb
Even if we are not consuming this presently, we would now have it available to SearchWorks if we need to move away from relying on reading 590 MARC.
Unsure if the multiple client calls in the `bound_with_parents` method is too inefficient, open to thoughts, but via APIs it is necessary. 
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/881
=> Index information about a holding's Bound-with parent item

lib/traject/config/folio_config.rb, lib/traject/config/sirsi_config.rb
We access course reserve related info for many fields. This change ensures that it's easier to alter where the info comes from (for FOLIO), and that information is loaded at most once per record.
Also turns off fetching of course reserve info from dump files for FOLIO indexing, so that it's easier to see what data is actually missing. Right now everything looks like it's working, because we're still loading the old course dump files in searchworks-folio-test.
Supports https://github.com/sul-dlss/searchworks_traject_indexer/issues/667; largely copied from https://github.com/sul-dlss/searchworks_traject_indexer/pull/686.
=> Course reserves indexing refactor for Sirsi

lib/folio/mhld_builder.rb, spec/integration/folio_config_spec.rb
This creates parity with the current approach:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/config/sirsi_config.rb#L2505-L2507
(`$a` is the statement, `$z` is the note)
=> Also include holdings notes in MHLD statements 

config/deploy.rb
Replaces #915 
Foreman says it shouldn't be added to the Gemfile (although I'm not personally convinced?), but it seems like we should want it installed as part of the deploy to ensure it is available.
=> Install foreman as part of the deploy.

lib/folio/mhld_builder.rb, spec/lib/folio/mhld_builder_spec.rb
So it doesn't break on unparsable values like 'WIN ' (see a12092671)
=> Improve date parsing

lib/folio_record.rb, lib/traject/config/folio_config.rb
These are "shadowed" in symphony at the item level and don't make it to our Symphony-based indexer at all.
=> Skip FOLIO records with only suppressed items

lib/folio_record.rb, spec/lib/folio_record_spec.rb
The current implementation can inject data into an existing 590 field. I think we actually want the logic to be more like:
- if there's already a bound-with 590 (e.g. it has both a subfield a + c), do nothing.
- otherwise, if there's bound-with data from FOLIO, add a new 590 field for each bound-with parent
- leave any other 590 fields alone (e.g. the 590 field with a subfield 'a' with "MARCit brief record" that's not giving bound-with information)
=> Simplify generated bound-with 590 logic

lib/traject/config/sirsi_config.rb, spec/lib/traject/config/access_spec.rb, spec/lib/traject/config/item_info_spec.rb
=> Omit the on-order placeholder for incomplete bound-with records

lib/folio_record.rb, lib/traject/config/folio_config.rb, lib/traject/readers/folio_postgres_reader.rb, spec/lib/folio_record_spec.rb
Fixes #921 
Lane is currently storing their electronic access in a MARC MHLD record. In FOLIO, they'd like to use FOLIO's native electronic access statements stored on their holdings record. We can ignore any data in the MARC bib records (so we don't have to have complicated merge logic).
=> Derive MARC 856 field data from FOLIO electronic access statements

Gemfile, Gemfile.lock, config/boot.rb
Currently jruby does not support zeitwerk when loading a singleton (such as LocationMap) 
See https://github.com/jruby/jruby/issues/6781
This was causing errors like `NameError: uninitialized constant CallNumbers::ShelfkeyBase` when running in production (but not in tests sadly). (https://app.honeybadger.io/projects/57331/faults/97129515)
=> Revert using zeitwerk

lib/traject/readers/folio_postgres_reader.rb
=> Separate data retrieval from updated date filtering

lib/traject/readers/folio_postgres_reader.rb
After a full reindex, the catchup query was taking an hour or more. This gets that query time back to ~3 minutes and the normal "5 minute delta" query time in just a couple seconds.
=> Postgres query performance tweaks

lib/folio_record.rb
…to better match the FOLIO UI's notion:
https://github.com/folio-org/stripes-util/blob/54db030221abd25b202bdcdbe7e34d9e396ff7dc/lib/effectiveCallNumber.js#L27-L35
Note that we're deliberately omitting the copy number.
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/954
=> Add volume + chronology to the generated item callnumber 

lib/locations_map.rb, spec/integration/compare_sirsi_and_folio_spec.rb, spec/lib/folio/eresource_holdings_builder_spec.rb
=> Map SUL/SDR location to SUL/INTERNET for parity

config/settings.yml, script/process_folio_postgres_to_kafka.rb
This is a stepping stone to switching puppet to set the right settings variable (e.g. `SETTINGS__enviornments__folio_test__database_url`?) instead of DATABASE_URL so we can easily support different FOLIO environments.
=> Access the FOLIO database url through the environment settings

config/settings.yml
24 seems to work ok on Monday 🤷‍♂️ 
Follow-on to #956
=> Add `full_dump_processes` configuration for folio_test

lib/traject/readers/folio_postgres_reader.rb
FOLIO keeps (all? some?) versions of the source records around.
=> Only retrieve ACTUAL source records.

lib/folio_record.rb, spec/integration/folio_config_spec.rb
~~There's possibly more to do here, but the more I look at it the more confused I get. Other possible item statuses to location mappings are:~~
Additional mappings:
`'On order' => 'ON-ORDER'`
`'In process (non-requestable)' => 'INPROCESS' ` ~~OR 'AT-REPAIR' or 'BINDERY' (or other BIND code)~~
~~`'Awaiting pickup' => "#{library_code}-LOAN"` (but how to know at which service desk?)~~
~~`'Awaiting delivery' => "#{library_code}-LOAN"` (but how to know at which service desk?)~~
Mapped `Awaiting delivery` to GRE-LOAN for lack of a more generic code.
~~Not clear whether these should map to a current location in item_display or not.~~
Closes #937
=> Map FOLIO item statuses to item_display current locations

lib/traject/config/sirsi_config.rb
Fixes:
```
ArgumentError:
comparison of Array with Array failed
Shared Example Group: "records match" called from ./spec/integration/compare_sirsi_and_folio_spec.rb:146
```
=> FOLIO barcodes are nil-able and ruby doesn't like sorting strings vs nil

lib/traject/readers/folio_postgres_reader.rb
=> Filter out staffOnly notes

lib/traject/readers/folio_postgres_reader.rb, spec/lib/traject/readers/folio_postgres_reader_spec.rb
This also gives us a way to benchmark in order to see if we've adversely impacted the performance of the query.
=> Write a test that shows that the query is valid

lib/traject/readers/folio_postgres_reader.rb
=> Be consistent with SQL formatting

lib/folio_record.rb, spec/lib/folio_record_spec.rb
These aren't present in the Symphony MARC record and make looking for indexing differences annoying.
=> Strip subfield 0 data that starts with (SIRSI)

spec/integration/compare_sirsi_and_folio_spec.rb
`skip` short-circuits the test execution, and there's no sense trying to run `nil` through the indexer and wait for it to blow up.
=> Get a better pending message if there's no FOLIO record

lib/folio_record.rb, lib/sirsi_holding.rb, spec/lib/folio_record_spec.rb
This starts to handle one of the ways the FOLIO on-order data is modeled for migrated data.
Open questions (probably for future work) include:
Part of #768 , at least sufficient to get instances with only on-order data indexed.
=> Add stub on-order holdings for FOLIO for instances with only on-order holdings

lib/folio/eresource_holdings_builder.rb, spec/integration/folio_config_spec.rb, spec/lib/folio/eresource_holdings_builder_spec.rb
=> Use the holdingType value (or inferred type from the location) to determine if something is an electronic holding

lib/traject/readers/folio_postgres_reader.rb
Copy/pasted HRIDs can have uppercase letters (e.g. L123), but the query wants lower-case values only.
=> Downcase the provided hrid/catkey value when searching

lib/traject/readers/folio_postgres_reader.rb
`jsonb->>'name'` isn't indexed, triggering a table scan. I'm not sure how much we should expect this table to grow, but 🤷
=> Update statistical code query to hit an index

lib/folio_record.rb
Regression from #985 now that the `map` can break early.
=> Use filter_map when generating holdings

lib/folio/mhld_builder.rb
Some FOLIO-native records have holdings records with nil values: 
```
"holdingsStatements"=>[nil],
```
🤷‍♂️ 
Fixes #1010
=> Filter holdings statements; apparently FOLIO leaves garbage around

lib/folio/mhld_builder.rb, spec/lib/folio/mhld_builder_spec.rb
=> Handle holding records that have neither a chronology nor enumeration

lib/folio/mhld_builder.rb, spec/integration/folio_config_spec.rb
We definitely don't want to render latest received data that looks like "2022 ()". That's not what the old code did.
In trying to find examples of data, I think I discovered our logic to retrieve the latest pieces is tied to the holdings, but our holdings statements (and other data derived from the MHLD) are stored on a different holdings record.
=> Display latest received data correctly

lib/traject/readers/folio_postgres_reader.rb
The upstream functions suppress notes that aren't explicitly set to `staffOnly=false`, e.g.:
```
SELECT jsonb_agg(DISTINCT e)
FROM ( SELECT e - 'holdingsNoteTypeId' - 'staffOnly' ||
jsonb_build_object('holdingsNoteTypeName', ( SELECT jsonb ->> 'name'
FROM holdings_note_type
WHERE id = nullif(e ->> 'holdingsNoteTypeId','')::uuid )) e
FROM jsonb_array_elements( $1 ) AS e
WHERE NOT (e ->> 'staffOnly')::bool ) e1
```
Turns out, notes created in FOLIO don't set `staffOnly` for public notes. 
fixes #1018
=> Upstream FOLIO functions remove all natively created notes

spec/lib/traject/readers/folio_postgres_reader_spec.rb
=> Add more benchmarking for FOLIO queries

lib/traject/readers/folio_postgres_reader.rb
We previously filtered out notes from items + holdings (#983) but it turns out instances also have staff-only notes.
=> Filter out staff-only instance notes; fixes #1045

lib/traject/config/sirsi_config.rb
Lane currently stores their era data in 660/661 for some reason.
Part of #1038
=> Index 660y and 661y into the `era_facet` field

lib/traject/config/folio_config.rb
Because we load the sirsi config after overriding reserves_lookup,
we weren't actually turning off the lookup of old course reserve
data, so it was being used at index time to populate item_display
and other fields.
This changes the order so that we override the method after loading
the sirsi_config.
=> Ensure we disable old course reserves lookup during indexing

lib/sirsi_holding.rb, spec/lib/sirsi_holding_spec.rb
Continuation of #1057 ; we're guarding against nil call numbers in so many other places, it seems like we should do so here too.
=> Guard against nil call numbers

lib/folio_record.rb, spec/integration/folio_config_spec.rb
After #1054, we can get items without a corresponding holding record when it's in the migrate-err location. 
Fixes #1072 1072
=> Skip items with a suppressing or migrate-err holdings record

Gemfile, Gemfile.lock, lib/traject/readers/folio_postgres_reader.rb, script/load_folio_postgres_full.sh, script/process_folio_postgres_to_kafka.rb
```
usage: script/process_folio_postgres_to_kafka.rb [options]
--help           
--kafka-topic    The kafka topic used for writing records
--verbose        
--processes      Number of parallel processes to spawn to handle querying
State management
--state-file     
--no-state-file  do not use the state file to track the current query time
--full           enable full indexing (vs delta indexing, that uses the modified timestamp from the state file)
SQL query options
--sql-query      a list of additional SQL filters to apply to the query
--sql-join       an additional SQL join query to apply to the underlying query
```
=> Update FolioPostgresReader to accept 'addl_from' clauses for filtering

lib/folio_record.rb, spec/lib/folio_record_spec.rb
e.g. course reserves desks. This should allow us to display FOLIO data more like Symphony:
Current behavior:
Symphony behavior:
=> Treat some temporary locations as if they were the permanent locations

script/process_folio_postgres_to_kafka.rb
This might be faster than waiting for FOLIO's queries for some smaller collections. I'm not sure it's _that_ much faster in practice, but seems handy to have available 🤷‍♂️ 
The FOLIO UI's "download identifiers" provides them as quoted strings (reusing some CSV escaping code??), so I've accounted for that too.
=> Add support for indexing from a list of FOLIO ids

lib/locations_map.rb, spec/integration/compare_sirsi_and_folio_spec.rb
E.g. Symphony codes MUS/MEMLIBMUS and MUS/LOCKED-STK are both mapped to the FOLIO location `MUS-LOCKED`. For our backwards-compatible mappings, we don't want to use `MUS/MEMLIBMUS` because it... isn't right.
=> Exclude some Symphony/FOLIO mappings that we don't want to use to populate `item_display`

spec/integration/compare_sirsi_and_folio_spec.rb
I got this backwards -- `true` means filter the data by sometime, `false` means return the original data (for modification).
=> Flip fields filter condition

lib/folio/mhld_builder.rb, lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/lib/folio/mhld_builder_spec.rb
- Don't filter out holdings and items in *-MIGRATE-ERR locations
- Remove check for skipping indexing of records with all suppressed items
=> Allow indexing of holdings and items in MIGRATE-ERR locations

spec/lib/traject/config/callnum_facet_spec.rb
This helps reduce the calls to record_with_999, so we can remove it in the future
=> Refactor LC callnum specs

spec/lib/traject/config/callnum_facet_spec.rb
Reduces number of places record_with_999 is called
=> Refactor tests for invalid LC callnumbers

lib/sirsi_holding.rb, spec/lib/traject/config/callnum_facet_spec.rb
All callnumber types are from FolioRecord#call_number_type_map and EDI-REMOVE is not one of the returned values
=> Remove a call number type that can not be expressed in Folio

spec/lib/traject/config/genre_spec.rb
Thought I would try an easy 999 removal first. I was ready to rewrite this test, but I fail to see how it's relevant to the genre field at all. The test right above it is almost exactly the same. There is no reference to 999 in the `genre_ssim` code in `folio_config`.
=> Remove MARC 999 reference from genre_spec

lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/lib/folio_record_spec.rb
We always want to generate item records for FOLIO items (that aren't suppressed) and FOLIO bound-with holdings.
We should fall-back on generating a stub record for eResources, and if there aren't eResources fall back on an on-order record (either because there is an PO line or a `596a`  in the MARC (for now...))
This refactor hopefully makes that relationship clearer, and gets rid of the implicitly created on-order stub.
=> Tweak when we're generating stub FOLIO items

spec/lib/traject/config/format_main_spec.rb
A lot of these tests just include 999 fields even though the code doesn't care about them.
=> Reduce use of 999 field in format_main spec

spec/lib/traject/config/callnum_facet_spec.rb
There is no code for call num types other than Dewey or LC, so we don't need to explicitly test every combination of that. We also don't need to test invalid LC or Dewey with any other context as we already have tests for that
=> Remove duplicate or unnecessary callnum_facet tests

config/settings.yml
2x the processes doesn't make that big a difference, but maybe keeps the database happier.. and we still keep ahead of the indexers.
=> Halve the number of full-dump processes

lib/traject/config/folio_config.rb, spec/lib/traject/config/url_spec.rb
E.g. https://gryphon-search.stanford.edu/view/10452961.. presumably a data error, but we ended up with many of them in the FOLIO migration.
=> Guard against blank 856u values

lib/folio_record.rb, spec/lib/folio_record_spec.rb
Some records in FOLIO have a holdings type Bound-with, but we couldn't automatically link them to an item record. This PR adds a stub item record to create parity with Symphony.
=> Create stub bound-with holdings for bound-withs without an item

lib/sirsi_holding.rb
Confirmed HILA has call numbers that start with XX, e.g.
```
"a4086108","XX015"
"a4086131","XX048"
"a4086140","XX058"
"a4086148","XX066"
"a4086151","XX069"
"a4086163","XX090"
"a4086200","XX136"
```
(But `HILA` also has the normal `XX(` temp call numbers too)
It looks like all the true "temp" call numbers start with `XX(`, so... we just use that?
=> Expand TEMP_CALLNUM_PREFIX to match the actual migrated data

lib/folio/marc_record_mapper.rb, spec/lib/folio_record_spec.rb
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/1196
It's unclear how objects come to be in this state (and the graphql schema seems to think it's invalid too), but 🤷‍♂️
=> Guard against nil values for electronicAccess

spec/lib/traject/config/sirsi_config_spec.rb
Because Folio doesn't use these
Ref #1189
=> Avoid MARC 999 fields in symphony config test

lib/traject/config/folio_config.rb
- correct the file name
- add the solr document id (because `source_record_id` is just the UUID)
> 2023-09-06T07:42:10-07:00 DEBUG folio_config.rb Processed bf47f18b-3617-5862-bc76-b682777cc658 (a13454724) (0.025s)
=> Improve end-of-processing logging

spec/lib/traject/config/format_main_spec.rb, spec/lib/traject/config/sirsi_config_spec.rb
This makes the tests more clear about which behavior is being exercised
=> Don't stub holdings when we aren't using them

config/deploy.rb
`User` is unnecessary (and possibly harmful?) for user-level systemd services.
=> Remove User attributes from the service definition

spec/lib/traject/config/location_facet_spec.rb
The folio_config looks at holdings, so set them up in the test
Ref #1189
=> Remove MARC 999 fields from facet spec

lib/traject/config/folio_config.rb
This reduces the kafka fetch queue size from 100 to 25 (so we're only buffering 1/4 the number of FOLIO records). This appears to reduce the memory needd without impacting throughput.
=> Reduce memory needs for FOLIO indexing

spec/lib/traject/config/item_info_spec.rb
Folio uses holding records and not 999s, so this test is now more reflective of what we're doing with Folio data
=> Rewrite item_info specs to avoid MARC 999

spec/lib/traject/config/subject_spec.rb
Folio does not use MARC 999, so just stub the holdings instead
=> Avoid relying on MARC 999 records for testing

spec/lib/traject/config/item_info_spec.rb
Because FOLIO doesn't use 999 fields
=> Avoid using MARC 999 fields in barcode_search test

.rubocop.yml, lib/folio/eresource_holdings_builder.rb, lib/folio_holding.rb, lib/folio_record.rb, spec/lib/folio/eresource_holdings_builder_spec.rb, spec/lib/folio_record_spec.rb
I think the two functional changes are:
- bound-withs are no longer necessarily SEE-OTHER (which... turns out not to be true in Symphony for some `GREEN/FED-DOCS`). Searchworks is figuring out something is bound-with from the holdings type, so the location code can be whatever.
- barcodes are optional; I think we resolved anything downstream in searchworks that required a barcode?
Fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/1058
=> Extract FolioHolding

lib/folio_holding.rb, lib/folio_record.rb, spec/lib/folio_holding_spec.rb
This is especially useful for bound-with availability lookup.
The data is redundant for normal holdings, but included for consistency.
=> Add the instance id + hrid to the item display struct

config/boot.rb, lib/folio_record.rb
This fixes <internal:/Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- folio_holding (LoadError) when doing folio_download_record.rb"
=> Move require to boot

spec/lib/traject/config/folio_course_reserves_spec.rb
Closes #1112
All of the remaining tests from sirsi_course_reserves_spec were
made obsolete by our new strategy; this is the only piece of
functionality that we didn't have under Symphony that needs
testing.
=> Add a test for courses_json_struct

lib/traject/config/folio_config.rb, spec/lib/traject/config/subject_spec.rb
The only use I can see downstream is:
> fetch(:collection_struct, []).reject { |collection| collection[:source] == 'SDR-PURL' }
=> Update collection_struct to use the source 'marc' instead of 'sirsi'

lib/folio/marc_record_mapper.rb, spec/lib/traject/config/genre_spec.rb
Fixes #1252
This scrubs any subfields with the value NoExport, so they don't
get indexed or displayed in any way in SearchWorks. Unclear who
is using this other than Lane, but it seemed like a safe interpretation
of "NoExport" to mean "pretend it doesn't exist in a discovery
environment".
=> Remove NoExport subfields from MARC

lib/locations_map.rb
This handles a case where the FOLIO temp location of MEDIA-CRES was
mapped to MEDIA-CENTER for its library, which wasn't a library
in Symphony. We're currently preserving the symphony library codes
to pass to SW, so we need to rewrite it to MEDIA-MTXT.
See record https://searchworks.stanford.edu/view/12377736
=> Rewrite MEDIA-CENTER to MEDIA-MTXT in LocationsMap

lib/traject/readers/kafka_folio_reader.rb, lib/traject/readers/kafka_purl_fetcher_reader.rb
Maybe there's a zeitwerk way to do this, but it'd be really nice to get the stats reporting back before trying to dig into that.
=> Restore kafka/statsd consumer stats reporting

lib/traject/readers/folio_postgres_reader.rb, script/process_folio_postgres_to_kafka.rb
As of November 2023, postgres seems like it isn't coming up with a great query plan for our massive indexing query. Splitting it into 2 parts (ids to index / the full json blob) seems to persuade the postgres to make a better plan. It's unclear what changed postgres from filtering and then retrieving to "construct the big blobs of JSON for every instance and then filter out the ~200 that are actually relevant", but here we are.
Future work may include:
- building a kafka topic of changed ids and then consuming that list (better parallelization for handling deltas?)
- revisiting this partition if/when FOLIO cascades updated timestamps so query conditions are a little more straightforward
- figure out the right query plan hints to get postgres to do the right thing
- ??
Compared to …
=> Fetch documents to index by instance id before retrieving the full document to index

lib/folio_record.rb, spec/lib/folio_record_spec.rb
This is a work-around so e-resources show up as a course reserve.
Fixes https://github.com/sul-dlss/SearchWorks/issues/3689
=> Include course reserves data for suppressed items

lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb
This fixes #1305, which will restore the relations widget in
Earthworks for scanned map content once it is reindexed.
=> Allow non-geo content types to point to source collection

Gemfile, Gemfile.lock, README.md, config/settings.yml, lib/sdr_events.rb, lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb, spec/lib/sdr_events_spec.rb
Closes #1299 
I tested this with some geo content in argo-stage. Druid [bd882yq4680](https://argo-stage.stanford.edu/view/druid:bd882yq4680) successfully received a message from the indexer:
Druid [yy029tb6261](https://argo-stage.stanford.edu/view/druid:yy029tb6261) was not indexed because the indexer couldn't transform its bounding box into valid data at index-time, and it received an appropriate message:
=> Report indexing status to SDR during geo indexing

lib/traject/config/geo_config.rb
Closes #1300
We may later come along and change these file paths to point to stacks instead, but in the meantime, this is a simple change to make.
=> Add a link to geoblacklight references for ISO19110 XML

lib/traject/config/geo_config.rb, spec/integration/geo_config_spec.rb
GeoBlacklight records don't have an id field like SearchWorks ones
do - instead they have the layer_id_s field (in v1.0 schema), which
is set to the prefixed druid. This has to be set in the traject
context so that the indexer issues a delete using the id that the
record will actually have.
Fixes #597
=> Ensure correct record id is set to enable deletion from geoblacklight

lib/traject/config/folio_config.rb
It is indeed used in Searchworks.
=> Fix comment about vern_title_uniform_display

lib/traject/readers/folio_postgres_reader.rb
=> Re-add nolano tables to the tables map instead of specifying them directly

lib/traject/common/marc_utils.rb, lib/traject/config/folio_config.rb, spec/lib/traject/config/note_fields_spec.rb
This avoids useless data like this:
```ruby
[{:fields=>[], :label=>"Summary", :unmatched_vernacular=>[]}, {:fields=>[], :label=>"Content advice", :unmatched_vernacular=>[]}]
```
As seen on records like https://searchworks.stanford.edu/view/2472159
=> Don't index summary_struct when there is no data

lib/folio/eresource_holdings_builder.rb, spec/lib/folio/eresource_holdings_builder_spec.rb
Lane wasn't using holdings types in their migrated data, but their newly created resources seem to have it (although they still don't use the "Electronic" value..)
=> Fix bug with identifying electronic holdings locations; fixes #1346

lib/call_numbers/dewey.rb, lib/call_numbers/dewey_shelfkey.rb, lib/call_numbers/lc.rb, lib/call_numbers/other.rb, lib/call_numbers/shelfkey.rb, lib/call_numbers/shelfkey_base.rb, lib/folio_item.rb, lib/traject/config/folio_config.rb, spec/factories/holdings.rb, spec/lib/traject/config/item_info_spec.rb, spec/lib/traject/config/preferred_barcode_spec.rb
This refactor pushes the `volume_info` data even further down; this time the shelfkey implementations get to take volume information into account.
Includes #1371 and a hint of #1370. Merge those first.
=> Provide volume_info to each call number class as a separate arg

spec/lib/traject/config/preferred_barcode_spec.rb
The underlying expectation of these tests hasn't changed; we're now just treating them (correctly) with a separate call number and an enumeration.
=> Fix a testing conflict after multiple PRs were merged

lib/call_numbers/dewey_shelfkey.rb, lib/call_numbers/lc.rb, lib/call_numbers/lc_shelfkey.rb, lib/call_numbers/other.rb, lib/call_numbers/other_shelfkey.rb, lib/call_numbers/shelfkey_base.rb, spec/lib/call_numbers/lc_shelfkey_spec.rb, spec/lib/call_numbers/other_spec.rb, spec/lib/traject/config/preferred_barcode_spec.rb
This attempts to get some consistency in our shelfkey classes. It's a little extra code (for the moment), but this will make it easier to junk the `CallNumbers::LC`, `CallNumbers::Dewey`, etc classes soon.
=> Reorganize the shelfkey classes

lib/traject/config/folio_config.rb, spec/integration/folio_config_spec.rb, spec/lib/traject/config/preferred_barcode_spec.rb
This gives us a seam to extract browse nearby information from the `item_display_struct`, and should allow us to separate the items for "At the library" from the spines used for browsing. 
https://github.com/sul-dlss/SearchWorks/pull/4041 is the related Searchworks PR to use this data.
When we switch to using the FOLIO holding's call number data, we'll be able to clean up + consolidate the different types of call number objects floating around the indexer, and hopefully `call_number_object` + `call_number_for_item` will go away entirely.
=> Add `browse_nearby_struct` seam

lib/sdr_events.rb, lib/traject/config/geo_config.rb, lib/traject/writers/solr_better_json_writer.rb, spec/integration/geo_config_spec.rb, spec/lib/traject/writers/solr_better_json_writer_spec.rb
Closes #1321 
This refactors the SolrBetterJsonWriter so that there's a data structure that connects the desired actions (add/update vs. delete) to each document/ID. We then use that data to report the status of each record after communicating with solr, so that we can dispatch one message per druid indicating if the addition/deletion was successful or not.
The calls that currently do this in the indexer config are removed in favor of doing it in the writer, since it's more accurate to report based on the actual Solr response.
=> Reporting indexing events to SDR based on solr responses

lib/traject/readers/folio_postgres_reader.rb, spec/lib/traject/readers/folio_postgres_reader_spec.rb
In my research I tried Unicode normalization with this set of characters. It did not work. From what I can gather U+FE20 and U+FE21 are specific marks that don't have any correlation with   U+0361. 
Closes https://github.com/sul-dlss/SearchWorks/issues/4010
=> replace half diacritics U+FE20, U+FE21 with correct diacritic U+0361

lib/traject/config/folio_config.rb, spec/integration/folio_config_spec.rb
This will allow us to continue to support https://github.com/sul-dlss/SearchWorks/issues/3944 after we remove e-resources from the `item_display_struct`.
=> Index the FOLIO library codes into holdings_library_code_ssim

lib/folio_record.rb
This lets us appropriately lop e.g. bound-with alphanum call numbers
=> Always pass the FOLIO record to the item

lib/traject/config/folio_config.rb, spec/integration/folio_config_spec.rb
This should be closer to parity with the stub e-resource items we used to create prior to #1381; otherwise we end up excluding records with e.g. SFX urls (e.g. `a12195945`)
=> Index records with any marc links data, not just a full text url

lib/traject/config/folio_config.rb, spec/lib/traject/config/browse_nearby_spec.rb
This fixes a regression from #1381 that caused us to use the browseable call numbers on any thing with an e-resource, not just the ones without an item.
=> Exclude the browseable call numbers from the MARC if we skipped items because of its call number type

lib/folio_item.rb, lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/factories/holdings.rb, spec/lib/folio_holding_spec.rb
Reviewing #1389 + #1379, I was getting confused about which holding was which. I think by being explicit within FolioItem about when we're using the bound-with holding + instance data, it'll be clearer.
=> Refactor FolioItem to pass the bound-with information as the original holding

lib/folio_item.rb, spec/lib/traject/config/browse_nearby_spec.rb
Bound-with call numbers are funny. The bound-with child holdings record contains both the call number and the volume/enumeration/etc information in the `callNumber` field. Most of the time, the bound-with child call number is similar to the bound-with parent item's call number and we're able to extract the volume information. Sometimes, the bound-with call number is totally different and we should just use the holding's call number as-is.
=> Handle bound-with call numbers a little better

lib/traject/config/folio_config.rb, spec/lib/traject/config/browse_nearby_spec.rb
E.g. the holdings record on https://searchworks.stanford.edu/view/L74649/  has the call number "Karger". We'd rather use the browseable LC  call number.
=> Use browseable call numbers for Lane e-resources with other data in the holdings call number

lib/traject/readers/folio_postgres_reader.rb, spec/lib/traject/readers/folio_postgres_reader_spec.rb
This reverts commit a1af7586ba0e31479138d496ad7a7a6de1a7a5fc.
It looks like we're converting too many things to diacritics, e.g. https://link.gale.com/apps/ECCO?u=stan90222 from a5530417
=> Revert "replace half diacritics U+FE20, U+FE21 with full diactritic U+0361"

.rubocop.yml, .rubocop_todo.yml, lib/folio/marc_record_instance_mapper.rb, lib/folio/marc_record_mapper.rb, lib/folio_item.rb, lib/folio_record.rb, spec/factories/holdings.rb, spec/fixtures/files/folio_bw_principal.json, spec/lib/folio_record_spec.rb, spec/lib/traject/config/browse_nearby_spec.rb, spec/lib/traject/config/item_info_spec.rb
The bound-with principal ("parent") holdings record will (now) always have a bound-with item attached to it (its own item)  to ~obscure~ make the bound-with parent and bound-with children have the same data structure. Without doing anything, we'll end up duplicating the bound-with parent data (showing the actual item and the supposedly-bound-with holding item) e.g. https://searchworks.stanford.edu/view/290907...
So we need to do something to suppress that extra data. Unfortunately, not all our bound-with holdings have the bound-with holdings type, so we get to try our best to de-duplicate 🤷‍♂️
=> Filter out bound-with parents that seem to be bound-with itself

lib/folio_record.rb, lib/traject/config/folio_config.rb, spec/integration/compare_against_solrmarc_docs_spec.rb, spec/lib/traject/config/access_spec.rb, spec/lib/traject/config/holdings_spec.rb, spec/lib/traject/config/item_info_spec.rb
Kevin determined there's only ~150 items with a 596 without any holdings record, and gryphon-search was ok dropping the 596 logic and remediating the data at some future point.
=> Stop using MARC 596 for on-order information

lib/traject/config/folio_config.rb, spec/lib/traject/config/managed_purl_spec.rb
Fixes SW-4341
(See e.g. https://searchworks.stanford.edu/view/12113412.json for `collection:a4719997` instead of `collection:4719997` like all the other objects)
=> Strip the leading a from catkeys in collection fields

config/deploy/prod.rb
After #1448 was merged, I ran the infrastructure integration tests and confirmed that items released from argo-stage were correctly indexed using the new config. This is ready to go.
Once merged, https://github.com/sul-dlss/earthworks/pull/963 is unblocked.
=> Index Aardvark records for production Earthworks

lib/traject/config/geo_aardvark_config.rb, lib/traject/macros/cocina.rb, lib/traject/macros/geo.rb, lib/translation_maps/geo_resource_class.yaml, spec/fixtures/files/df451fk6628.json, spec/fixtures/files/df451fk6628.meta_json, spec/fixtures/files/gm036df2527.json, spec/fixtures/files/gm036df2527.meta_json, spec/fixtures/files/rk962wd2562.json, spec/fixtures/files/rk962wd2562.meta_json, spec/integration/geo_aardvark_config_spec.rb
Closes https://github.com/sul-dlss/earthworks/issues/1114
Addresses items 1 and 2.
Partially addresses item 3 (add the DOI to the data but doesn't display it), it is now stored in the index.
Addresses 4 (the boolean `gbl_georeferenced_b` field).
Also adds `dct_realtion_sm` to hold the link as requested.
=> Modify Geo Aardvard mappings

lib/traject/config/geo_aardvark_config.rb, spec/integration/geo_aardvark_config_spec.rb
Closes https://github.com/sul-dlss/earthworks/issues/1127
I tested this by modifying one of the geoblacklight fixtures to have this format, and checking the UI.
=> Geo Aardvark: Use hash variant to store downloadUrl in dct_references_s

lib/traject/config/geo_aardvark_config.rb, spec/fixtures/files/yx324nv8969.json, spec/fixtures/files/yx324nv8969.meta_json, spec/integration/geo_aardvark_config_spec.rb
=> Ensure only items with a druid are linked in dc_source_sm

lib/traject/config/geo_aardvark_config.rb, lib/traject/macros/extras.rb, lib/utils.rb, spec/integration/geo_aardvark_config_spec.rb
required for https://github.com/sul-dlss/earthworks/pull/1315 to work
part of https://github.com/sul-dlss/earthworks/issues/1136
=> geo_aardvark_config.rb: add_date_hierarchy_sm field

lib/traject/common/marc_utils.rb
After #784, we were silently dropping relator terms that don't match the expected list instead of passing them through.
=> Fix a relator-terms regression from #784

lib/utils.rb, spec/lib/utils_spec.rb
Attempts to fix https://github.com/sul-dlss/SearchWorks/issues/4010. I think we should merge this and run a full reindex in -test and take a look at the results to see if it breaks anything 🤷‍♂️
=> Re-enable cyrillic encoding cleanup

lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
right now we are always including includedInDataCatalog even if it isn't included in the dataCatalog. This should fix that.
=> don't include earthworks in schema.org spec if not in earthworks

lib/utils.rb, spec/lib/utils_spec.rb
We know this is a safe operation, as JSON is required to be UTF-8 encoded and the whole payload is JSON
Fixes #1589
=> Set encoding to UTF-8 before trying to fix UTF-8 characters

lib/call_numbers/other_shelfkey.rb, lib/call_numbers/sudoc_shelfkey.rb, lib/folio_item.rb, lib/traject/config/folio_config.rb, spec/lib/call_numbers/other_shelfkey_spec.rb, spec/lib/call_numbers/sudoc_shelfkey_spec.rb, spec/lib/traject/config/browse_nearby_spec.rb
Part of #1562 
Adds support for SuDoc shelfkeys for browse nearby.
For the shelfkey I'm ordering the entire call number and there is quite the diverse set. Ultimately it isn't doing anything that fancy beyond trying to determine what is likely a year versus just a number. "Words" sort alphabetically. That seems to be the norm and they tend to be very late in the call number, in which case you rarely see them because they are consolidated behind the lopped call number. I think user feedback would be extremely valuable. I suspect there could be a range of practices that users would discover. It's a challenge to sample 2+ million call numbers.
As opposed to shelfkeys, here lopped call numbers are depending on the (mostly) consistent stem + book number part of the suffix. This seemed correct, …
=> Generate Sudoc shelfkeys

Gemfile, Gemfile.lock, lib/call_numbers/caldoc_shelfkey.rb, lib/folio_item.rb, lib/traject/config/folio_config.rb, spec/factories/holdings.rb, spec/lib/call_numbers/caldoc_shelfkey_spec.rb, spec/lib/traject/config/browse_nearby_spec.rb, spec/lib/traject/config/item_info_spec.rb
Part of #1562.
Previously CalDocs where going through the "OTHER" call number shelfkey path. This adds specific handling for CalDocs.
There seems to be a mix of practices/conventions in the data in what is included in the base call number versus the volume info. This work is prioritizing the data in the base call number (not trying to infer intent of volume info) as that is what is most visible to the user in the browse nearby spines.
=> Add CalDoc specific shelfkeys

lib/call_numbers/shelfkey_base.rb
closes https://github.com/sul-dlss/SearchWorks/issues/4797
The reason this wasn't working was the parent record had the reverse_shelf key: `en~0~~~zwtu}szzzzz~ez}uwzzzz~r 000001 nr 000001 001933 maj ` with a space at the end. The problem is the search was escaping the space to `en~0~~~zwtu}szzzzz~ez}uwzzzz~r 000001 nr 000001 001933 maj\` so when we were doing a matching https://github.com/sul-dlss/SearchWorks/blob/2bbe292af1bc73ed3ebe21420d79cb3bb161b0d7/app/models/nearby_on_shelf.rb#L44 the search reverse_shelfkey wasn't matching due to the space. Removing trailing spaces from indexing will clean up this up.
=> remove trailing space from reverse_shelfkey

lib/traject/config/folio_config.rb, lib/traject/config/folio_format_config.rb, lib/traject/macros/extras.rb, lib/traject/macros/folio_format.rb, spec/lib/traject/config/folio_format_config_spec.rb, spec/lib/traject/macros/extras_spec.rb, spec/lib/traject/macros/folio_format_spec.rb
- Introduce `ResourceType` Traject macro module
- Define reusable matchers leader?, control_field_byte?, marc_subfield?
- Add literal_multiple method to Traject macro Extras
For reference see these files with the proposed changes and rules:
https://docs.google.com/document/d/1xR0cInOS2wlMzqGGY9ZLbxRb5PdUJ3b6jhnO6xr_upE/edit?tab=t.0
https://docs.google.com/spreadsheets/d/1NK5M1Ti8UG0XSfnRBWkgnF-seevfZWe3nEBowlV7R1g/edit?gid=0#gid=0
This PR does not cover every line, only the first few resource types. After the pattern is established and merged, I can continue down the list.
So this won't fully close #1632 but gets us partway there.
The macros take inspiration from `traject_plus` as well as the conditional logic included in Exhibits indexing.
=> Add hierarchical field format_hsim to Folio indexing

lib/traject/config/folio_config.rb
About a dozen items in Folio have Caldocs marked as Sudocs, resulting in the call number being stored twice. This is a relevancy issue because they have double the term frequency.
=> Do not index CALDOC call numbers as SUDOCs

lib/traject/config/sdr_config.rb, spec/integration/sdr_config_spec.rb
In https://github.com/sul-dlss/SearchWorks/pull/1186, we started looking in `pub_year_ss` instead, and we stopped looking in these fields entirely in https://github.com/sul-dlss/SearchWorks/commit/e5941d27d4eb7dd1465176efafe68e7efb00de74.
=> Remove unused date fields for MODS.

lib/public_cocina_record.rb, lib/public_xml_record.rb, lib/purl_record.rb, spec/fixtures/files/hn730ks3626.json, spec/fixtures/files/nj770kg7809.json, spec/fixtures/files/sg213ph2100.json, spec/integration/sdr_config_spec.rb
This is a step toward decoupling from public XML and getting the values directly from the canonical Cocina
=> Use the label from the cocina record
